import requests
import threading
import queue
import time
import sqlite3
from urllib.parse import quote
from typing import Dict, List, Tuple
from datetime import datetime
import os
import sys
from getpass import getpass
from colorama import init, Fore, Style

init()

def animate_text(text: str, color: str = Fore.CYAN, delay: float = 0.03):
    for char in text:
        sys.stdout.write(color + char + Style.RESET_ALL)
        sys.stdout.flush()
        time.sleep(delay)
    print()

ARIVA_BANNER = """
   ┌──────────────────────────────────────────────────┐
   │    █████╗ ██████╗ ██╗██╗   ██╗ █████╗    │
   │   ██╔══██╗██╔══██╗██║██║   ██║██╔══██╗   │
   │   ███████║██████╔╝██║██║   ██║███████║   │
   │   ██╔══██║██╔══██╗██║██║   ██║██╔══██║   │
   │   ██║  ██║██║  ██║██║╚██████╔╝██║  ██║   │
   │   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝   │
   └──────────────────────────────────────────────────┘
"""

def startup_animation():
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Fore.CYAN + "─" * 60 + Style.RESET_ALL)
    animate_text("ARIVA | Kullanıcı Adı Denetleyicisi", Fore.MAGENTA, 0.02)
    time.sleep(0.3)
    print(Fore.GREEN + ARIVA_BANNER + Style.RESET_ALL)
    animate_text("ARİVA LOCK v5.0 | MADE BY SAMET HAN & ATAHAN ARSLAN", Fore.RED, 0.02)
    time.sleep(0.5)
    print(Fore.CYAN + "─" * 60 + Style.RESET_ALL)

def check_password():
    correct_password = "ariva"
    attempts = 3
    while attempts > 0:
        print(Fore.CYAN + "\n" + "═" * 50 + Style.RESET_ALL)
        animate_text("Erişim Kodu Gerekiyor: ", Fore.MAGENTA, 0.02)
        password = getpass("")
        if password == correct_password:
            animate_text("✓ Erişim Onaylandı", Fore.GREEN, 0.02)
            time.sleep(0.5)
            return True
        else:
            attempts -= 1
            animate_text(f"✗ Erişim Reddedildi | Kalan: {attempts}", Fore.RED, 0.02)
            time.sleep(1)
    animate_text("✗ Çok Fazla Hatalı Deneme | Kapatılıyor...", Fore.RED, 0.02)
    time.sleep(1)
    sys.exit()

class UsernameChecker:
    def __init__(self):
        self.sites = {
            "Twitter": "https://twitter.com/{}",
            "Instagram": "https://instagram.com/{}",
            "GitHub": "https://github.com/{}",
            "Reddit": "https://reddit.com/user/{}",
            "Facebook": "https://facebook.com/{}",
            "LinkedIn": "https://linkedin.com/in/{}",
            "YouTube": "https://youtube.com/@{}",
            "Pinterest": "https://pinterest.com/{}",
            "Twitch": "https://twitch.tv/{}",
            "Steam": "https://steamcommunity.com/id/{}",
            "Medium": "https://medium.com/@{}",
            "TikTok": "https://tiktok.com/@{}",
            "Snapchat": "https://snapchat.com/add/{}",
            "Telegram": "https://t.me/{}",
            "Discord": "https://discord.com/users/{}",
            "Tumblr": "https://{}.tumblr.com",
            "Vimeo": "https://vimeo.com/{}",
            "SoundCloud": "https://soundcloud.com/{}",
            "DeviantArt": "https://{}.deviantart.com",
            "Flickr": "https://flickr.com/people/{}",
            "Behance": "https://behance.net/{}",
            "Dribbble": "https://dribbble.com/{}",
            "Quora": "https://quora.com/profile/{}",
            "Patreon": "https://patreon.com/{}",
            "Etsy": "https://etsy.com/shop/{}",
            "Goodreads": "https://goodreads.com/{}",
            "Mixcloud": "https://mixcloud.com/{}",
            "CodePen": "https://codepen.io/{}",
            "Bitbucket": "https://bitbucket.org/{}",
            "StackOverflow": "https://stackoverflow.com/users/{}",
            "GitLab": "https://gitlab.com/{}",
            "Last.fm": "https://last.fm/user/{}",
            "ReverbNation": "https://reverbnation.com/{}",
            "Bandcamp": "https://{}.bandcamp.com",
            "Newgrounds": "https://{}.newgrounds.com",
            "500px": "https://500px.com/{}",
            "About.me": "https://about.me/{}",
            "CashApp": "https://cash.app/${}",
            "Venmo": "https://venmo.com/{}",
            "Keybase": "https://keybase.io/{}",
            "Fiverr": "https://fiverr.com/{}",
            "Upwork": "https://upwork.com/freelancers/{}",
            "Freelancer": "https://freelancer.com/u/{}",
            "Trello": "https://trello.com/{}",
            "ProductHunt": "https://producthunt.com/@{}",
            "AngelList": "https://angel.co/u/{}",
            "HackerRank": "https://hackerrank.com/{}",
            "LeetCode": "https://leetcode.com/{}",
            "Chess.com": "https://chess.com/member/{}",
            "Lichess": "https://lichess.org/@/{}",
            "Hepsiburada": "https://www.hepsiburada.com/{}",
            "Trendyol": "https://www.trendyol.com/{}",
            "Sahibinden": "https://www.sahibinden.com/{}",
            "N11": "https://www.n11.com/{}",
            "Gittigidiyor": "https://www.gittigidiyor.com/{}",
            "Letgo": "https://www.letgo.com/tr-tr/{}",
            "EksiSozluk": "https://eksisozluk.com/{}",
            "UludagSozluk": "https://www.uludagsozluk.com/{}",
            "InciSozluk": "https://www.incisozluk.com.tr/{}",
            "DonanimHaber": "https://forum.donanimhaber.com/{}",
            "ShiftDelete": "https://forum.shiftdelete.net/{}",
            "Webtekno": "https://www.webtekno.com/{}",
            "HaberTurk": "https://www.haberturk.com/{}",
            "Milliyet": "https://www.milliyet.com.tr/{}",
            "Hurriyet": "https://www.hurriyet.com.tr/{}",
            "Sabah": "https://www.sabah.com.tr/{}",
            "CNNturk": "https://www.cnnturk.com/{}",
            "NTV": "https://www.ntv.com.tr/{}",
            "Sozcu": "https://www.sozcu.com.tr/{}",
            "Posta": "https://www.posta.com.tr/{}",
            "Aksam": "https://www.aksam.com.tr/{}",
            "Vatan": "https://www.gazetevatan.com/{}",
            "Radikal": "https://www.radikal.com.tr/{}",
            "Zaman": "https://www.zaman.com.tr/{}",
            "T24": "https://t24.com.tr/{}",
            "Birgun": "https://www.birgun.net/{}",
            "Evrensel": "https://www.evrensel.net/{}",
            "Diken": "https://www.diken.com.tr/{}",
            "OdaTV": "https://www.odatv4.com/{}",
            "Yenicag": "https://www.yenicaggazetesi.com.tr/{}",
            "Kizlarsoruyor": "https://www.kizlarsoruyor.com/{}",
            "Onedio": "https://onedio.com/{}",
            "Memurlar": "https://forum.memurlar.net/{}",
            "KPSScafe": "https://www.kpsscafe.com.tr/{}",
            "Egitimajansi": "https://www.egitimajansi.com/{}",
            "Eokul": "https://e-okul.meb.gov.tr/{}",
            "MEB": "https://www.meb.gov.tr/{}",
            "YOK": "https://www.yok.gov.tr/{}",
            "OSYM": "https://www.osym.gov.tr/{}",
            "TurkiyeGov": "https://www.turkiye.gov.tr/{}",
            "IstanbulEdu": "https://www.istanbul.edu.tr/{}",
            "AnkaraEdu": "https://www.ankara.edu.tr/{}",
            "Hacettepe": "https://www.hacettepe.edu.tr/{}",
            "ODTU": "https://www.metu.edu.tr/{}",
            "Boun": "https://www.boun.edu.tr/{}",
            "ITU": "https://www.itu.edu.tr/{}",
            "KocaeliEdu": "https://www.kocaeli.edu.tr/{}",
            "EgeEdu": "https://www.ege.edu.tr/{}",
            "DokuzEylul": "https://www.deu.edu.tr/{}",
            "AkdenizEdu": "https://www.akdeniz.edu.tr/{}",
            "UludagEdu": "https://www.uludag.edu.tr/{}",
            "YildizEdu": "https://www.yildiz.edu.tr/{}",
            "MarmaraEdu": "https://www.marmara.edu.tr/{}",
            "GaziEdu": "https://www.gazi.edu.tr/{}",
            "SakaryaEdu": "https://www.sakarya.edu.tr/{}",
            "SelcukEdu": "https://www.selcuk.edu.tr/{}",
            "ErciyesEdu": "https://www.erciyes.edu.tr/{}",
            "CukurovaEdu": "https://www.cu.edu.tr/{}",
            "KaradenizEdu": "https://www.ktu.edu.tr/{}",
            "AtaturkEdu": "https://www.atauni.edu.tr/{}",
            "TrakyaEdu": "https://www.trakya.edu.tr/{}",
            "PamukkaleEdu": "https://www.pau.edu.tr/{}",
            "AdnanMenderes": "https://www.adu.edu.tr/{}",
            "SuleymanDemirel": "https://www.sdu.edu.tr/{}",
            "InonuEdu": "https://www.inonu.edu.tr/{}",
            "FiratEdu": "https://www.firat.edu.tr/{}",
            "DicleEdu": "https://www.dicle.edu.tr/{}",
            "YuzuncuYil": "https://www.yyu.edu.tr/{}",
            "HarranEdu": "https://www.harran.edu.tr/{}",
            "GaziantepEdu": "https://www.gantep.edu.tr/{}",
            "KonyaTeknik": "https://www.ktun.edu.tr/{}",
            "NecmettinErbakan": "https://www.erbakan.edu.tr/{}",
            "AfyonEdu": "https://www.aku.edu.tr/{}",
            "AhiEvran": "https://www.ahievran.edu.tr/{}",
            "AmasyaEdu": "https://www.amasya.edu.tr/{}",
            "ArtvinEdu": "https://www.artvin.edu.tr/{}",
            "AydinEdu": "https://www.aydin.edu.tr/{}",
            "BalikesirEdu": "https://www.balikesir.edu.tr/{}",
            "BartinEdu": "https://www.bartin.edu.tr/{}",
            "BayburtEdu": "https://www.bayburt.edu.tr/{}",
            "BilecikEdu": "https://www.bilecik.edu.tr/{}",
            "BingolEdu": "https://www.bingol.edu.tr/{}",
            "BitlisEdu": "https://www.beu.edu.tr/{}",
            "BozokEdu": "https://www.bozok.edu.tr/{}",
            "BursaTeknik": "https://www.btu.edu.tr/{}",
            "CanakkaleEdu": "https://www.comu.edu.tr/{}",
            "CelalBayar": "https://www.cbu.edu.tr/{}",
            "CumhuriyetEdu": "https://www.cumhuriyet.edu.tr/{}",
            "DuzceEdu": "https://www.duzce.edu.tr/{}",
            "EskisehirOsmangazi": "https://www.ogu.edu.tr/{}",
            "GebzeTeknik": "https://www.gtu.edu.tr/{}",
            "HakkariEdu": "https://www.hakkari.edu.tr/{}",
            "HatayEdu": "https://www.hatay.edu.tr/{}",
            "HititEdu": "https://www.hitit.edu.tr/{}",
            "IgdirEdu": "https://www.igdir.edu.tr/{}",
            "IspartaEdu": "https://www.isparta.edu.tr/{}",
            "KafkasEdu": "https://www.kafkas.edu.tr/{}",
            "KahramanmarasEdu": "https://www.ksu.edu.tr/{}",
            "KarabukEdu": "https://www.karabuk.edu.tr/{}",
            "KastamonuEdu": "https://www.kastamonu.edu.tr/{}",
            "KilisEdu": "https://www.kilis.edu.tr/{}",
            "KirikkaleEdu": "https://www.kku.edu.tr/{}",
            "KirklareliEdu": "https://www.klu.edu.tr/{}",
            "KocaeliSaglik": "https://www.kocaelisaglik.edu.tr/{}",
            "KonyaGida": "https://www.gidatarim.edu.tr/{}",
            "KutahyaEdu": "https://www.dpu.edu.tr/{}",
            "MalatyaEdu": "https://www.malatya.edu.tr/{}",
            "ManisaEdu": "https://www.manisa.edu.tr/{}",
            "MardinEdu": "https://www.mardin.edu.tr/{}",
            "MuglaEdu": "https://www.mu.edu.tr/{}",
            "MusEdu": "https://www.mus.edu.tr/{}",
            "NevsehirEdu": "https://www.nevsehir.edu.tr/{}",
            "NigdeEdu": "https://www.nigde.edu.tr/{}",
            "OndokuzMayis": "https://www.omu.edu.tr/{}",
            "OrduEdu": "https://www.odu.edu.tr/{}",
            "OsmaniyeEdu": "https://www.osmaniye.edu.tr/{}",
            "RizeEdu": "https://www.erdogan.edu.tr/{}",
            "SiirtEdu": "https://www.siirt.edu.tr/{}",
            "SinopEdu": "https://www.sinop.edu.tr/{}",
            "SivasEdu": "https://www.sivas.edu.tr/{}",
            "TarsusEdu": "https://www.tarsus.edu.tr/{}",
            "TokatEdu": "https://www.gop.edu.tr/{}",
            "TrabzonEdu": "https://www.trabzon.edu.tr/{}",
            "TunceliEdu": "https://www.tunceli.edu.tr/{}",
            "UsakEdu": "https://www.usak.edu.tr/{}",
            "YalovaEdu": "https://www.yalova.edu.tr/{}",
            "YozgatEdu": "https://www.yozgat.edu.tr/{}",
            "ZonguldakEdu": "https://www.beun.edu.tr/{}",
            "AdiyamanEdu": "https://www.adiyaman.edu.tr/{}",
            "AgriEdu": "https://www.agri.edu.tr/{}",
            "ArdahanEdu": "https://www.ardahan.edu.tr/{}",
            "BatmanEdu": "https://www.batman.edu.tr/{}",
            "BurdurEdu": "https://www.mehmetakif.edu.tr/{}",
            "CankiriEdu": "https://www.cankiri.edu.tr/{}",
            "CorumEdu": "https://www.hitit.edu.tr/{}",
            "DenizliEdu": "https://www.pau.edu.tr/{}",
            "DiyarbakirEdu": "https://www.dicle.edu.tr/{}",
            "EdirneEdu": "https://www.trakya.edu.tr/{}",
            "ElazigEdu": "https://www.firat.edu.tr/{}",
            "ErzincanEdu": "https://www.erzincan.edu.tr/{}",
            "ErzurumEdu": "https://www.atauni.edu.tr/{}",
            "EskisehirTeknik": "https://www.eskisehir.edu.tr/{}",
            "GiresunEdu": "https://www.giresun.edu.tr/{}",
            "GumushaneEdu": "https://www.gumushane.edu.tr/{}",
            "IstanbulTeknik": "https://www.itu.edu.tr/{}",
            "IzmirBakircay": "https://www.bakircay.edu.tr/{}",
            "IzmirDemokrasi": "https://www.idu.edu.tr/{}",
            "IzmirKatip": "https://www.ikc.edu.tr/{}",
            "IzmirYuksek": "https://www.iyte.edu.tr/{}",
            "KayseriEdu": "https://www.kayseri.edu.tr/{}",
            "KirsehirEdu": "https://www.ahievran.edu.tr/{}",
            "KonyaSelcuk": "https://www.selcuk.edu.tr/{}",
            "KutahyaSaglik": "https://www.ksbu.edu.tr/{}",
            "MalatyaTurgut": "https://www.turgutozal.edu.tr/{}",
            "MersinEdu": "https://www.mersin.edu.tr/{}",
            "SamsunEdu": "https://www.samsun.edu.tr/{}",
            "SanliurfaEdu": "https://www.harran.edu.tr/{}",
            "TekirdagEdu": "https://www.nku.edu.tr/{}",
            "VanEdu": "https://www.yyu.edu.tr/{}",
            "Bilkent": "https://www.bilkent.edu.tr/{}",
            "KocUni": "https://www.ku.edu.tr/{}",
            "SabanciUni": "https://www.sabanciuniv.edu/{}",
            "Bahcesehir": "https://www.bau.edu.tr/{}",
            "Ozyegin": "https://www.ozyegin.edu.tr/{}",
            "IstanbulBilgi": "https://www.bilgi.edu.tr/{}",
            "Yeditepe": "https://www.yeditepe.edu.tr/{}",
            "IsikUni": "https://www.isikun.edu.tr/{}",
            "MaltepeUni": "https://www.maltepe.edu.tr/{}",
            "Beykent": "https://www.beykent.edu.tr/{}",
            "KadirHas": "https://www.khas.edu.tr/{}",
            "IstanbulAydin": "https://www.aydin.edu.tr/{}",
            "IstanbulKultur": "https://www.iku.edu.tr/{}",
            "IstanbulSehir": "https://www.sehir.edu.tr/{}",
            "IstanbulTicaret": "https://www.ticaret.edu.tr/{}",
            "Altinbas": "https://www.altinbas.edu.tr/{}",
            "UskudarUni": "https://www.uskudar.edu.tr/{}",
            "Medipol": "https://www.medipol.edu.tr/{}",
            "Acibadem": "https://www.acibadem.edu.tr/{}",
            "TOBB": "https://www.etu.edu.tr/{}",
            "Atilim": "https://www.atilim.edu.tr/{}",
            "CankayaUni": "https://www.cankaya.edu.tr/{}",
            "Baskent": "https://www.baskent.edu.tr/{}",
            "UfukUni": "https://www.ufuk.edu.tr/{}",
            "TEDUni": "https://www.tedu.edu.tr/{}",
            "AnkaraYildirim": "https://www.ybu.edu.tr/{}",
            "AnkaraBilim": "https://www.ankara.edu.tr/{}",
            "HacettepeTip": "https://www.hacettepe.edu.tr/{}",
            "AnkaraSosyal": "https://www.asbu.edu.tr/{}",
            "IzmirEkonomi": "https://www.ieu.edu.tr/{}",
            "YasarUni": "https://www.yasar.edu.tr/{}",
            "IzmirTinaztepe": "https://www.tinaztepe.edu.tr/{}",
            "AntalyaBilim": "https://www.antalya.edu.tr/{}",
            "AlanyaAlaaddin": "https://www.alanya.edu.tr/{}",
            "AkdenizKarpaz": "https://www.akun.edu.tr/{}",
            "KonyaKaratay": "https://www.karatay.edu.tr/{}",
            "Istanbul29Mayis": "https://www.29mayis.edu.tr/{}",
            "FatihSultan": "https://www.fsm.edu.tr/{}",
            "IbnHaldun": "https://www.ihu.edu.tr/{}",
            "IstanbulMedeniyet": "https://www.medeniyet.edu.tr/{}",
            "IstanbulRumeli": "https://www.rumeli.edu.tr/{}",
            "IstanbulSafa": "https://www.safa.edu.tr/{}",
            "IstanbulTopkapi": "https://www.topkapi.edu.tr/{}",
            "BeykozUni": "https://www.beykoz.edu.tr/{}",
            "DogusUni": "https://www.dogus.edu.tr/{}",
            "HaliçUni": "https://www.halic.edu.tr/{}",
            "IstanbulEsnaf": "https://www.iesu.edu.tr/{}",
            "IstanbulKent": "https://www.kent.edu.tr/{}",
            "IstanbulOkan": "https://www.okan.edu.tr/{}",
            "IstanbulYeni": "https://www.yeniyuzyil.edu.tr/{}",
            "Nisantasi": "https://www.nisantasi.edu.tr/{}",
            "PiriReis": "https://www.pirireis.edu.tr/{}",
            "SankoUni": "https://www.sanko.edu.tr/{}",
            "TorosUni": "https://www.toros.edu.tr/{}",
            "UskudarSaglik": "https://www.uskudar.edu.tr/{}",
            "HasanKalyoncu": "https://www.hku.edu.tr/{}",
            "IstinyeUni": "https://www.istinye.edu.tr/{}",
            "KapadokyaUni": "https://www.kapadokya.edu.tr/{}",
            "KonyaUgur": "https://www.ugur.edu.tr/{}",
            "LokmanHekim": "https://www.lokmanhekim.edu.tr/{}",
            "SemerkandUni": "https://www.semerkand.edu.tr/{}",
            "TarsusUni": "https://www.tarsus.edu.tr/{}",
            "TurkHava": "https://www.thk.edu.tr/{}",
            "YuksekIhtisas": "https://www.yiu.edu.tr/{}",
            "ZirveUni": "https://www.zirve.edu.tr/{}",
            "AkevUni": "https://www.akev.edu.tr/{}",
            "AlanyaHamdi": "https://www.alanya.edu.tr/{}",
            "AntalyaAkev": "https://www.akev.edu.tr/{}",
            "AvrasyaUni": "https://www.avrasya.edu.tr/{}",
            "BiruniUni": "https://www.biruni.edu.tr/{}",
            "CagUni": "https://www.cag.edu.tr/{}",
            "DemirogluBilim": "https://www.demiroglu.edu.tr/{}",
            "EurasiaUni": "https://www.eurasia.edu.tr/{}",
            "FenerbahceUni": "https://www.fbu.edu.tr/{}",
            "GedikUni": "https://www.gedik.edu.tr/{}",
            "IstanbulAtlas": "https://www.atlas.edu.tr/{}",
            "IstanbulGalata": "https://www.galata.edu.tr/{}",
            "IstanbulGelişim": "https://www.gelisim.edu.tr/{}",
            "IstanbulSBU": "https://www.sbu.edu.tr/{}",
            "KonyaGidaTarim": "https://www.gidatarim.edu.tr/{}",
            "MEFUni": "https://www.mef.edu.tr/{}",
            "MilliSavunma": "https://www.msu.edu.tr/{}",
            "PolisAkademisi": "https://www.pa.edu.tr/{}",
            "SaglikBilimleri": "https://www.sbu.edu.tr/{}",
            "TicaretUni": "https://www.ticaret.edu.tr/{}",
            "TurkAlman": "https://www.tau.edu.tr/{}",
            "TurkJaponya": "https://www.tju.edu.tr/{}",
            "UskudarBilim": "https://www.uskudar.edu.tr/{}",
            "YalovaSosyal": "https://www.yalova.edu.tr/{}",
            "YuksekIhtisasUni": "https://www.yiu.edu.tr/{}",
            "AnadoluAjansi": "https://www.aa.com.tr/{}",
            "TRT": "https://www.trt.net.tr/{}",
            "DHA": "https://www.dha.com.tr/{}",
            "IHA": "https://www.iha.com.tr/{}",
            "BloombergHT": "https://www.bloomberght.com/{}",
            "Ahaber": "https://www.ahaber.com.tr/{}",
            "ShowTV": "https://www.showtv.com.tr/{}",
            "KanalD": "https://www.kanald.com.tr/{}",
            "ATV": "https://www.atv.com.tr/{}",
            "StarTV": "https://www.startv.com.tr/{}",
            "FoxTV": "https://www.fox.com.tr/{}",
            "TV8": "https://www.tv8.com.tr/{}",
            "BeyazTV": "https://www.beyaztv.com.tr/{}",
            "HalkTV": "https://www.halktv.com.tr/{}",
            "Tele1": "https://www.tele1.com.tr/{}",
            "Kanal24": "https://www.kanal24.com.tr/{}",
            "UlkeTV": "https://www.ulketv.com.tr/{}",
            "TGRT": "https://www.tgrthaber.com.tr/{}",
            "NTVSpor": "https://www.ntvspor.net/{}",
            "Aspor": "https://www.aspor.com.tr/{}",
            "TRTSpor": "https://www.trtspor.com.tr/{}",
            "LigTV": "https://www.ligtv.com.tr/{}",
            "Fanatik": "https://www.fanatik.com.tr/{}",
            "Fotomac": "https://www.fotomac.com.tr/{}",
            "Sporx": "https://www.sporx.com/{}",
            "Mackolik": "https://www.mackolik.com/{}",
            "Sahadan": "https://www.sahadan.com/{}",
            "Iddaa": "https://www.iddaa.com/{}",
            "Misli": "https://www.misli.com/{}",
            "Bilyoner": "https://www.bilyoner.com/{}",
            "Nesine": "https://www.nesine.com/{}",
            "Tuttur": "https://www.tuttur.com/{}",
            "Bahis": "https://www.bahis.com/{}",
            "Turkcell": "https://www.turkcell.com.tr/{}",
            "VodafoneTR": "https://www.vodafone.com.tr/{}",
            "TurkTelekom": "https://www.turktelekom.com.tr/{}",
            "Bim": "https://www.bim.com.tr/{}",
            "A101": "https://www.a101.com.tr/{}",
            "Sok": "https://www.sokmarket.com.tr/{}",
            "Migros": "https://www.migros.com.tr/{}",
            "CarrefourSA": "https://www.carrefoursa.com/{}",
            "Getir": "https://getir.com/{}",
            "Yemeksepeti": "https://www.yemeksepeti.com/{}",
            "Banabi": "https://banabi.yemeksepeti.com/{}",
            "HizliGetir": "https://www.hizligetir.com/{}",
            "TrendyolGo": "https://www.trendyol.com/go/{}",
            "IstanbulKart": "https://www.istanbulkart.istanbul/{}",
            "EGO": "https://www.ego.gov.tr/{}",
            "Izmirim": "https://www.izmirimkart.com.tr/{}",
            "KocaeliKart": "https://www.kocaelikart.com/{}",
            "AnkaraKart": "https://www.ankarakart.com.tr/{}",
            "BursaKart": "https://www.bursakart.com/{}",
            "AdanaKent": "https://www.adanakentkart.com/{}",
            "KonyaElkart": "https://www.elkart.com.tr/{}",
            "AntalyaKart": "https://www.antalyakart.com.tr/{}",
            "Eshot": "https://www.eshot.gov.tr/{}",
            "IETT": "https://www.iett.istanbul/{}",
            "MetroIstanbul": "https://www.metro.istanbul/{}",
            "TCDD": "https://www.tcdd.gov.tr/{}",
            "Pegasus": "https://www.flypgs.com/{}",
            "THY": "https://www.turkishairlines.com/{}",
            "AnadoluJet": "https://www.anadolujet.com/{}",
            "SunExpress": "https://www.sunexpress.com/{}",
            "OnurAir": "https://www.onurair.com.tr/{}",
            "Corendon": "https://www.corendonairlines.com/{}",
            "Obilet": "https://www.obilet.com/{}",
            "Biletix": "https://www.biletix.com/{}",
            "Enuygun": "https://www.enuygun.com/{}",
            "Turna": "https://www.turna.com/{}",
            "Biletall": "https://www.biletall.com/{}",
            "KamilKoc": "https://www.kamilkoc.com.tr/{}",
            "Pamukkale": "https://www.pamukkale.com.tr/{}",
            "MetroTurizm": "https://www.metroturizm.com.tr/{}",
            "Ulusoy": "https://www.ulusoy.com.tr/{}",
            "Varan": "https://www.varan.com.tr/{}",
            "Nilufer": "https://www.nilufer.com.tr/{}",
            "EfeTur": "https://www.efetur.com.tr/{}",
            "IstanbulSeyahat": "https://www.istanbulseyahat.com.tr/{}",
            "Hepsijet": "https://www.hepsijet.com/{}",
            "YurticiKargo": "https://www.yurticikargo.com/{}",
            "ArasKargo": "https://www.araskargo.com.tr/{}",
            "MNGKargo": "https://www.mngkargo.com.tr/{}",
            "PTT": "https://www.ptt.gov.tr/{}",
            "SuraKargo": "https://www.suratkargo.com.tr/{}",
            "UPStr": "https://www.ups.com.tr/{}",
            "DHLtr": "https://www.dhl.com.tr/{}",
            "FedExtr": "https://www.fedex.com/tr-tr/{}",
            "TNTtr": "https://www.tnt.com/tr/{}",
            "ZiraatBank": "https://www.ziraatbank.com.tr/{}",
            "GarantiBBVA": "https://www.garantibbva.com.tr/{}",
            "Akbank": "https://www.akbank.com/{}",
            "IsBankasi": "https://www.isbank.com.tr/{}",
            "Yapikredi": "https://www.yapikredi.com.tr/{}",
            "Halkbank": "https://www.halkbank.com.tr/{}",
            "Vakifbank": "https://www.vakifbank.com.tr/{}",
            "Denizbank": "https://www.denizbank.com/{}",
            "QNBFinans": "https://www.qnbfinansbank.com/{}",
            "TEB": "https://www.teb.com.tr/{}",
            "IngBank": "https://www.ing.com.tr/{}",
            "KuveytTurk": "https://www.kuveytturk.com.tr/{}",
            "Albaraka": "https://www.albaraka.com.tr/{}",
            "TurkiyeFinans": "https://www.turkiyefinans.com.tr/{}",
            "VakifKatilim": "https://www.vakifkatilim.com.tr/{}",
            "ZiraatKatilim": "https://www.ziraatkatilim.com.tr/{}",
            "EmlakKatilim": "https://www.emlakkatilim.com.tr/{}",
            "Papara": "https://www.papara.com/{}",
            "Ininal": "https://www.ininal.com/{}",
            "Paycell": "https://www.paycell.com.tr/{}",
            "Param": "https://www.param.com.tr/{}",
            "Tosla": "https://www.tosla.com/{}",
            "BKMExpress": "https://www.bkmexpress.com.tr/{}",
            "Iyzico": "https://www.iyzico.com/{}",
            "Paytr": "https://www.paytr.com/{}",
            "PayuTR": "https://www.payu.com.tr/{}",
            "Hepsipay": "https://www.hepsipay.com/{}",
            "Naber": "https://www.naber.com.tr/{}",
            "Bip": "https://bip.com/{}",
            "Yayin": "https://www.yayin.com.tr/{}",
            "Dsmart": "https://www.dsmart.com.tr/{}",
            "Tivibu": "https://www.tivibu.com.tr/{}",
            "Digiturk": "https://www.digiturk.com.tr/{}",
            "NetflixTR": "https://www.netflix.com/tr/{}",
            "Blutv": "https://www.blutv.com/{}",
            "PuhuTV": "https://puhutv.com/{}",
            "Exxen": "https://www.exxen.com/{}",
            "Gain": "https://www.gain.tv/{}",
            "MubiTR": "https://mubi.com/tr/{}",
            "AmazonPrimeTR": "https://www.primevideo.com/region/tr/{}",
            "DisneyPlusTR": "https://www.disneyplus.com/tr-tr/{}",
            "SporSmart": "https://www.sporsmart.com.tr/{}",
            "Sinemax": "https://www.sinemax.com.tr/{}",
            "Filmbox": "https://www.filmbox.com.tr/{}",
            "Turkmax": "https://www.turkmax.com.tr/{}",
            "Kanal7": "https://www.kanal7.com/{}",
            "TVnet": "https://www.tvnet.com.tr/{}",
            "HaberGlobal": "https://www.haberglobal.com.tr/{}",
            "BenguTurk": "https://www.benguturk.com/{}",
            "KRT": "https://www.krttv.com.tr/{}",
            "UlusalKanal": "https://www.ulusal.com.tr/{}",
            "CayTV": "https://www.caytv.com.tr/{}",
            "FlashTV": "https://www.flashtv.com.tr/{}",
            "TV5": "https://www.tv5.com.tr/{}",
            "YolTV": "https://www.yoltv.com.tr/{}",
            "Kemalist": "https://www.kemalist.com.tr/{}",
            "Aydinlik": "https://www.aydinlik.com.tr/{}",
            "Veryansin": "https://www.veryansintv.com/{}",
            "MilliGazete": "https://www.milligazete.com.tr/{}",
            "YeniMesaj": "https://www.yenimesaj.com.tr/{}",
            "YeniAsya": "https://www.yeniasya.com.tr/{}",
            "YeniBirlik": "https://www.yenibirlik.com.tr/{}",
            "YeniSafak": "https://www.yenisafak.com/{}",
            "TurkiyeGazetesi": "https://www.turkiyegazetesi.com.tr/{}",
            "Karar": "https://www.karar.com/{}",
            "Ortadogugazetesi": "https://www.ortadogugazetesi.com.tr/{}",
            "AydinHedef": "https://www.aydinhedef.com.tr/{}",
            "EgeTelgraf": "https://www.egetelgraf.com/{}",
            "GazeteDuvar": "https://www.gazeteduvar.com.tr/{}",
            "Halk54": "https://www.halk54.com/{}",
            "Izmir9Eylul": "https://www.izmir9eylul.com/{}",
            "KocaeliBaris": "https://www.kocaelibarisgazetesi.com/{}",
            "ManisaGundem": "https://www.manisagundemhaber.com/{}",
            "MersinHaber": "https://www.mersinhaber.com/{}",
            "SamsunHaber": "https://www.samsunhaber.com/{}",
            "TrabzonHaber": "https://www.trabzonhaber.com/{}",
            "AdanaHaber": "https://www.adanahaber.com/{}",
            "AnkaraHaber": "https://www.ankarahaber.com/{}",
            "AntalyaHaber": "https://www.antalyahaber.com/{}",
            "BursaHaber": "https://www.bursahaber.com/{}",
            "DenizliHaber": "https://www.denizlihaber.com/{}",
            "DiyarbakirHaber": "https://www.diyarbakirhaber.com/{}",
            "ErzurumHaber": "https://www.erzurumhaber.com/{}",
            "EskisehirHaber": "https://www.eskisehirhaber.com/{}",
            "GaziantepHaber": "https://www.gaziantephaber.com/{}",
            "HatayHaber": "https://www.hatayhaber.com/{}",
            "KayseriHaber": "https://www.kayserihaber.com/{}",
            "KonyaHaber": "https://www.konyahaber.com/{}",
            "MalatyaHaber": "https://www.malatyahaber.com/{}",
            "SanliurfaHaber": "https://www.sanliurfahaber.com/{}",
            "TekirdagHaber": "https://www.tekirdaghaber.com/{}",
            "VanHaber": "https://www.vanhaber.com/{}",
            "ZonguldakHaber": "https://www.zonguldakhaber.com/{}",
            "Haber61": "https://www.haber61.net/{}",
            "Haber7": "https://www.haber7.com/{}",
            "Haberler": "https://www.haberler.com/{}",
            "Internethaber": "https://www.internethaber.com/{}",
            "MyNet": "https://www.mynet.com/{}",
            "Sondakika": "https://www.sondakika.com/{}",
            "Takvim": "https://www.takvim.com.tr/{}",
            "TgrtHaber": "https://www.tgrthaber.com.tr/{}",
            "YurtGazetesi": "https://www.yurtgazetesi.com.tr/{}",
            "Emlakjet": "https://www.emlakjet.com/{}",
            "Zingat": "https://www.zingat.com/{}",
            "HurriyetEmlak": "https://www.hurriyetemlak.com/{}",
            "MilliyetEmlak": "https://www.milliyetemlak.com/{}",
            "SahibindenEmlak": "https://www.sahibinden.com/emlak/{}",
            "Evim": "https://www.evim.com.tr/{}",
            "Dekopasaj": "https://www.dekopasaj.com/{}",
            "Gardrops": "https://www.gardrops.com/{}",
            "Dolap": "https://www.dolap.com/{}",
            "Modacruz": "https://www.modacruz.com/{}",
            "Zebramo": "https://www.zebramo.com/{}",
            "IkinciEl": "https://www.ikinciel.com/{}",
            "Spot": "https://www.spot.com.tr/{}",
            "NaberNasılsın": "https://www.nabernasılsın.com/{}",
            "TurkChat": "https://www.turkchat.com/{}",
            "Sohbet": "https://www.sohbet.com.tr/{}",
            "ChatTR": "https://www.chattr.com/{}",
            "Geveze": "https://www.geveze.org/{}",
            "Zurna": "https://www.zurna.net/{}",
            "Mirc": "https://www.mirc.com.tr/{}",
            "Kelebek": "https://www.kelebek.com/{}",
            "CiftlikBank": "https://www.ciftlikbank.com/{}",
            "Farmasi": "https://www.farmasi.com.tr/{}",
            "AvonTR": "https://www.avon.com.tr/{}",
            "OriflameTR": "https://www.oriflame.com.tr/{}",
            "AmwayTR": "https://www.amway.com.tr/{}",
            "HerbalifeTR": "https://www.herbalife.com.tr/{}",
            "LRHealth": "https://www.lrworld.com/tr/{}",
            "TupperwareTR": "https://www.tupperware.com.tr/{}",
            "Kariyer": "https://www.kariyer.net/{}",
            "Eleman": "https://www.eleman.net/{}",
            "SecretCV": "https://www.secretcv.com/{}",
            "Yenibiris": "https://www.yenibiris.com/{}",
            "IndeedTR": "https://tr.indeed.com/{}",
            "JoobleTR": "https://tr.jooble.org/{}",
            "Işkur": "https://www.iskur.gov.tr/{}",
            "KamuPersonel": "https://www.kamupersonel.com/{}",
            "MemurAlim": "https://www.memuralim.com/{}",
            "EmlakKulisi": "https://www.emlakkulisi.com/{}",
            "EmlakPencerem": "https://www.emlakpencerem.com/{}",
            "EmlakWeb": "https://www.emlakweb.com/{}",
            "EmlakGundemi": "https://www.emlakgundemi.com.tr/{}",
            "EmlakDream": "https://www.emlakdream.com/{}",
            "EmlakHaber": "https://www.emlakhaber.com/{}",
            "OtoHaber": "https://www.otohaber.com.tr/{}",
            "Otoajanda": "https://www.otoajanda.com/{}",
            "Otomobil": "https://www.otomobil.com.tr/{}",
            "Arabam": "https://www.arabam.com/{}",
            "OtoKiralama": "https://www.otokiralama.com/{}",
            "Garenta": "https://www.garenta.com.tr/{}",
            "AvisTR": "https://www.avis.com.tr/{}",
            "BudgetTR": "https://www.budget.com.tr/{}",
            "EnterpriseTR": "https://www.enterprise.com.tr/{}",
            "SixtTR": "https://www.sixt.com.tr/{}",
            "Yolcu360": "https://www.yolcu360.com/{}",
            "RentGo": "https://www.rentgo.com/{}",
            "EtsTur": "https://www.etstur.com/{}",
            "JollyTur": "https://www.jollytur.com/{}",
            "TatilBudur": "https://www.tatilbudur.com/{}",
            "TatilSepeti": "https://www.tatilsepeti.com/{}",
            "Setur": "https://www.setur.com.tr/{}",
            "Anitur": "https://www.anitur.com.tr/{}",
            "Prontotour": "https://www.prontotour.com/{}",
            "KulturTur": "https://www.kulturtur.com/{}",
            "BookingTR": "https://www.booking.com/country/tr/{}",
            "TrivagoTR": "https://www.trivago.com.tr/{}",
            "AirbnbTR": "https://www.airbnb.com.tr/{}",
            "Otelz": "https://www.otelz.com/{}",
            "Neredekal": "https://www.neredekal.com/{}",
            "Tatilcom": "https://www.tatil.com/{}",
            "Gezimanya": "https://www.gezimanya.com/{}",
            "Yolrehberi": "https://www.yolrehberi.com/{}",
            "GeziYorum": "https://www.geziyorum.com/{}",
            "Seyahatname": "https://www.seyahatname.com/{}",
            "Rotasiz": "https://www.rotasiz.com/{}",
            "GeziAlemi": "https://www.gezialemi.com/{}",
            "TurizmHaber": "https://www.turizmhaber.com/{}",
            "TurizmGunlugu": "https://www.turizmgunlugu.com/{}",
            "TurizmAjansi": "https://www.turizmajansi.com/{}",
            "TurizmdeBuHafta": "https://www.turizmdebuhafta.com/{}",
            "TurizmTatil": "https://www.turizmtatil.com/{}",
            "KampYeri": "https://www.kampyeri.com/{}",
            "KampAlani": "https://www.kampalani.com/{}",
            "KampRehberi": "https://www.kamprehberi.com/{}",
            "DogaKampi": "https://www.dogakampi.com/{}",
            "KampKeyfi": "https://www.kampkeyfi.com/{}",
            "Kampciyiz": "https://www.kampciyiz.com/{}",
            "KampYapanlar": "https://www.kampyapanlar.com/{}",
            "KampGunlugu": "https://www.kampgunlugu.com/{}",
            "KampTurkiye": "https://www.kampturkiye.com/{}",
            "DogaSporlari": "https://www.dogasporlari.com/{}",
            "OutdoorTR": "https://www.outdoortr.com/{}",
            "DogaYasam": "https://www.dogayasam.com/{}",
            "DogaGezi": "https://www.dogagezi.com/{}",
            "DogaTutkunlari": "https://www.dogatutkunlari.com/{}",
            "BisikletTR": "https://www.bisiklet.com.tr/{}",
            "KoşuTR": "https://www.kosu.com.tr/{}",
            "YuzmeTR": "https://www.yuzme.com.tr/{}",
            "FitnessTR": "https://www.fitnesstr.com/{}",
            "SporSalonu": "https://www.sporsalonu.com/{}",
            "SporMerkezi": "https://www.spormerkezi.com/{}",
            "SporAkademi": "https://www.sporakademi.com/{}",
            "SporEgitim": "https://www.sporegitim.com/{}",
            "SporDunyasi": "https://www.spordunyasi.com/{}",
            "SporHaber": "https://www.sporhaber.com/{}",
            "SporGundem": "https://www.sporgundem.com/{}",
            "SporMagazin": "https://www.spormagazin.com/{}",
            "SporYorum": "https://www.sporyorum.com/{}",
            "SporAnaliz": "https://www.sporanaliz.com/{}",
            "SporTotem": "https://www.sportotem.com/{}",
            "SporVakti": "https://www.sporvakti.com/{}",
            "SporZamani": "https://www.sporzamani.com/{}",
            "SporKeyfi": "https://www.sporkeyfi.com/{}",
            "SporAşkı": "https://www.sporaski.com/{}",
            "SporRuh": "https://www.sporruh.com/{}",
            "SporHayat": "https://www.sporhayat.com/{}",
            "SporDergi": "https://www.spordergi.com/{}",
            "SporGazete": "https://www.sporgazete.com/{}",
            "SporTV": "https://www.sportv.com.tr/{}",
            "SporCanli": "https://www.sporcanli.com/{}",
            "Sporizle": "https://www.sporizle.com/{}",
            "SporLig": "https://www.sporlig.com/{}",
            "SporMac": "https://www.spormac.com/{}",
            "SporSkor": "https://www.sporskor.com/{}",
            "SporSonuc": "https://www.sporsonuc.com/{}",
            "SporTahmin": "https://www.sportahmin.com/{}",
            "SporBahis": "https://www.sporbahis.com/{}",
            "SporOyun": "https://www.sporoyun.com/{}",
            "SporEglence": "https://www.sporeglence.com/{}",
            "SporDost": "https://www.spordost.com/{}",
            "SporArkadas": "https://www.sporarkadas.com/{}",
            "SporToplulugu": "https://www.sportoplulugu.com/{}",
            "SporKulupleri": "https://www.sporkulupleri.com/{}",
            "SporFederasyon": "https://www.sporfederasyon.com/{}",
            "SporBakanligi": "https://www.sporgm.gov.tr/{}",
            "GenclikSpor": "https://www.gsb.gov.tr/{}",
            "SporTot": "https://www.sportoto.gov.tr/{}",
            "SporLoto": "https://www.sporloto.com.tr/{}",
            "MilliPiyango": "https://www.millipiyango.gov.tr/{}",
            "SayisalLoto": "https://www.sayisalloto.com.tr/{}",
            "SanalOyun": "https://www.sanaloyun.com/{}",
            "OyunTR": "https://www.oyun.com.tr/{}",
            "Zula": "https://www.zulaoyun.com/{}",
            "Metin2": "https://www.metin2.com.tr/{}",
            "KnightOnline": "https://www.knightonlineworld.com/{}",
            "Silkroad": "https://www.silkroadonline.net/{}",
            "CSGOtr": "https://www.csgo.com.tr/{}",
            "ValorantTR": "https://www.valorant.com/tr/{}",
            "PubgTR": "https://www.pubg.com/tr/{}",
            "FortniteTR": "https://www.fortnite.com/tr/{}",
            "LOLtr": "https://www.leagueoflegends.com/tr-tr/{}",
            "Dota2TR": "https://www.dota2.com/tr/{}",
            "FifaTR": "https://www.fifa.com/tr/{}",
            "PesTR": "https://www.pes.com.tr/{}",
            "OyunHaber": "https://www.oyunhaber.com/{}",
            "OyunDunyasi": "https://www.oyundunyasi.com/{}",
            "OyunKeyfi": "https://www.oyunkeyfi.com/{}",
            "OyunMerkezi": "https://www.oyunmerkezi.com/{}",
            "OyunForum": "https://www.oyunforum.com/{}",
            "OyunIndir": "https://www.oyunindir.com/{}",
            "OyunYukle": "https://www.oyunyukle.com/{}",
            "OyunOyna": "https://www.oyunoyna.com/{}",
            "OyunSkor": "https://www.oyunskor.com/{}",
            "OyunParki": "https://www.oyunparki.com/{}",
            "OyunAlani": "https://www.oyunalani.com/{}",
            "OyunEvi": "https://www.oyunevi.com/{}",
            "OyunDukkani": "https://www.oyundukkani.com/{}",
            "OyunMagaza": "https://www.oyunmagaza.com/{}",
            "OyunPazari": "https://www.oyunpazari.com/{}",
            "OyunSatis": "https://www.oyunsatis.com/{}",
            "OyunAlisveris": "https://www.oyunalisveris.com/{}",
            "OyunHobi": "https://www.oyunhobi.com/{}",
            "OyunTutku": "https://www.oyuntutku.com/{}",
            "OyunAskı": "https://www.oyunaski.com/{}",
            "OyunDostu": "https://www.oyundostu.com/{}",
            "OyunArkadasi": "https://www.oyunarkadasi.com/{}",
            "OyunToplulugu": "https://www.oyuntoplulugu.com/{}",
            "OyunKlan": "https://www.oyunklan.com/{}",
            "OyunTakim": "https://www.oyuntakim.com/{}",
            "OyunLigi": "https://www.oyunligi.com/{}",
            "OyunTurnuva": "https://www.oyunturnuva.com/{}",
            "OyunEtkinlik": "https://www.oyunetkinlik.com/{}",
            "OyunFestival": "https://www.oyunfestival.com/{}",
            "OyunFuar": "https://www.oyunfuar.com/{}",
            "OyunGunu": "https://www.oyungunu.com/{}",
            "OyunHaftasi": "https://www.oyunhaftasi.com/{}",
            "OyunSezon": "https://www.oyunsezon.com/{}",
            "OyunYili": "https://www.oyunyili.com/{}",
            "OyunTarih": "https://www.oyuntarih.com/{}",
            "OyunKultur": "https://www.oyunkultur.com/{}",
            "OyunSanat": "https://www.oyunsanat.com/{}",
            "OyunEgitim": "https://www.oyunegitim.com/{}",
            "OyunAkademi": "https://www.oyunakademi.com/{}",
            "OyunOkul": "https://www.oyunokul.com/{}",
            "OyunDers": "https://www.oyunders.com/{}",
            "OyunOgretmen": "https://www.oyunogretmen.com/{}",
            "OyunRehber": "https://www.oyunrehber.com/{}",
            "OyunYardim": "https://www.oyunyardim.com/{}",
            "OyunDestek": "https://www.oyundestek.com/{}",
            "OyunHizmet": "https://www.oyunhizmet.com/{}",
            "OyunServis": "https://www.oyunservis.com/{}",
            "OyunTeknik": "https://www.oyunteknik.com/{}",
            "OyunBilgi": "https://www.oyunbilgi.com/{}",
            "OyunRehberi": "https://www.oyunrehberi.com/{}",
            "OyunInceleme": "https://www.oyuninceleme.com/{}",
            "OyunYorum": "https://www.oyunyorum.com/{}",
            "OyunPuan": "https://www.oyunpuan.com/{}",
            "OyunDeger": "https://www.oyundeger.com/{}",
            "OyunTest": "https://www.oyuntest.com/{}",
            "OyunDeneme": "https://www.oyundeneme.com/{}",
            "OyunAnaliz": "https://www.oyunanaliz.com/{}",
            "OyunKarsilastir": "https://www.oyunkarsilastir.com/{}",
            "OyunSecim": "https://www.oyunsecim.com/{}",
            "OyunTercih": "https://www.oyuntercih.com/{}",
            "OyunFikir": "https://www.oyunfikir.com/{}",
            "OyunOneri": "https://www.oyunoneri.com/{}",
            "OyunTavsiye": "https://www.oyuntavsiye.com/{}",
            "OyunListe": "https://www.oyunliste.com/{}",
            "OyunSiralama": "https://www.oyunsiralama.com/{}",
            "OyunTop": "https://www.oyuntop.com/{}",
            "OyunEniyi": "https://www.oyuneniyi.com/{}",
            "OyunFavori": "https://www.oyunfavori.com/{}",
            "OyunPopuler": "https://www.oyunpopuler.com/{}",
            "OyunTrend": "https://www.oyuntrend.com/{}",
            "OyunGuncel": "https://www.oyunguncel.com/{}",
            "OyunYeni": "https://www.oyunyeni.com/{}",
            "OyunGelecek": "https://www.oyungelecek.com/{}",
            "OyunVizyon": "https://www.oyunvizyon.com/{}",
            "OyunHayal": "https://www.oyunhayal.com/{}",
            "OyunDus": "https://www.oyundus.com/{}",
            "OyunFantezi": "https://www.oyunfantezi.com/{}",
            "OyunMacera": "https://www.oyunmacera.com/{}",
            "OyunHeyecan": "https://www.oyunheyecan.com/{}",
            "OyunAdrenalin": "https://www.oyunadrenalin.com/{}",
            "OyunEfsane": "https://www.oyunefsane.com/{}",
            "OyunMit": "https://www.oyunmit.com/{}",
            "OyunDestan": "https://www.oyundestan.com/{}",
            "OyunHikaye": "https://www.oyunhikaye.com/{}",
            "OyunMasal": "https://www.oyunmasal.com/{}",
            "OyunSiir": "https://www.oyunsiir.com/{}",
            "OyunSarki": "https://www.oyunsarki.com/{}",
            "OyunMelodi": "https://www.oyunmelodi.com/{}",
            "OyunRitim": "https://www.oyunritim.com/{}",
            "OyunDans": "https://www.oyundans.com/{}",
            "OyunHareket": "https://www.oyunhareket.com/{}",
            "OyunEnerji": "https://www.oyunenerji.com/{}",
            "OyunGuc": "https://www.oyunguc.com/{}",
            "OyunZindelik": "https://www.oyunzindelik.com/{}",
            "OyunSaglik": "https://www.oyunsaglik.com/{}",
            "OyunForm": "https://www.oyunform.com/{}",
            "OyunFit": "https://www.oyunfit.com/{}",
            "OyunDenge": "https://www.oyundenge.com/{}",
            "OyunUyum": "https://www.oyunuyum.com/{}",
            "OyunAhenk": "https://www.oyunahenk.com/{}",
            "OyunBaris": "https://www.oyunbaris.com/{}",
            "OyunDostluk": "https://www.oyundostluk.com/{}",
            "OyunSevgi": "https://www.oyunsevgi.com/{}",
            "OyunAsk": "https://www.oyunask.com/{}",
            "OyunTutku": "https://www.oyuntutku.com/{}",
            "OyunBag": "https://www.oyunbag.com/{}",
            "OyunBagimlilik": "https://www.oyunbagimlilik.com/{}",
            "OyunHobi": "https://www.oyunhobi.com/{}",
            "OyunEglence": "https://www.oyuneglence.com/{}",
            "OyunMutluluk": "https://www.oyunmutluluk.com/{}",
            "OyunNeşe": "https://www.oyunnese.com/{}",
            "OyunGulus": "https://www.oyungulus.com/{}",
            "OyunKahkaha": "https://www.oyunkahkaha.com/{}",
            "OyunEspri": "https://www.oyunespri.com/{}",
            "OyunMizah": "https://www.oyunmizah.com/{}",
            "OyunKomedi": "https://www.oyunkomedi.com/{}",
            "OyunEglence": "https://www.oyuneglence.com/{}",
            "OyunSaka": "https://www.oyunsaka.com/{}",
            "OyunGulduru": "https://www.oyungulduru.com/{}",
            "OyunTiyatro": "https://www.oyuntiyatro.com/{}",
            "OyunSinema": "https://www.oyunsinema.com/{}",
            "OyunDizi": "https://www.oyundizi.com/{}",
            "OyunFilm": "https://www.oyunfilm.com/{}",
            "OyunVideo": "https://www.oyunvideo.com/{}",
            "OyunKlip": "https://www.oyunklip.com/{}",
            "OyunCanli": "https://www.oyuncanli.com/{}",
            "OyunYayin": "https://www.oyunyayin.com/{}",
            "OyunStream": "https://www.oyunstream.com/{}",
            "OyunKanal": "https://www.oyunkanal.com/{}",
            "OyunTV": "https://www.oyuntv.com/{}",
            "OyunRadyo": "https://www.oyunradyo.com/{}",
            "OyunMuzik": "https://www.oyunmuzik.com/{}",
            "OyunSes": "https://www.oyunses.com/{}",
            "OyunEfekt": "https://www.oyunefekt.com/{}",
            "OyunGrafik": "https://www.oyungrafik.com/{}",
            "OyunTasarim": "https://www.oyuntasarim.com/{}",
            "OyunKod": "https://www.oyunkod.com/{}",
            "OyunProgram": "https://www.oyunprogram.com/{}",
            "OyunYazilim": "https://www.oyunyazilim.com/{}",
            "OyunTeknoloji": "https://www.oyunteknoloji.com/{}",
            "OyunBilim": "https://www.oyunbilim.com/{}",
            "OyunArge": "https://www.oyunarge.com/{}",
            "OyunGeliştirme": "https://www.oyungelistirme.com/{}",
            "OyunProje": "https://www.oyunproje.com/{}",
            "OyunEkip": "https://www.oyunekip.com/{}",
            "OyunSirket": "https://www.oyunsirket.com/{}",
            "OyunFirma": "https://www.oyunfirma.com/{}",
            "OyunMarka": "https://www.oyunmarka.com/{}",
            "OyunEndustri": "https://www.oyunendustri.com/{}",
            "OyunSektor": "https://www.oyunsektor.com/{}",
            "OyunPazar": "https://www.oyunpazar.com/{}",
            "OyunTicaret": "https://www.oyunticaret.com/{}",
            "OyunEkonomi": "https://www.oyunekonomi.com/{}",
            "OyunFinans": "https://www.oyunfinans.com/{}",
            "OyunYatirim": "https://www.oyunyatirim.com/{}",
            "OyunKazan": "https://www.oyunkazan.com/{}",
            "OyunPara": "https://www.oyunpara.com/{}",
            "OyunGelir": "https://www.oyungelir.com/{}",
            "OyunKazanc": "https://www.oyunkazanc.com/{}",
            "OyunBasari": "https://www.oyunbasari.com/{}",
            "OyunZirve": "https://www.oyunzirve.com/{}",
            "OyunLider": "https://www.oyunlider.com/{}",
            "OyunKral": "https://www.oyunkral.com/{}",
            "OyunSampiyon": "https://www.oyunsampiyon.com/{}",
            "OyunEfsane": "https://www.oyunefsane.com/{}",
            "OyunUnlu": "https://www.oyununlu.com/{}",
            "OyunYildiz": "https://www.oyunyildiz.com/{}",
            "OyunIdol": "https://www.oyunidol.com/{}",
            "OyunKahraman": "https://www.oyunkahraman.com/{}",
            "OyunDestek": "https://www.oyundestek.com/{}",
            "OyunYardim": "https://www.oyunyardim.com/{}",
            "OyunRehber": "https://www.oyunrehber.com/{}",
            "OyunOgretmen": "https://www.oyunogretmen.com/{}",
            "OyunMentor": "https://www.oyunmentor.com/{}",
            "OyunDanisman": "https://www.oyundanisman.com/{}",
            "OyunUzman": "https://www.oyunuzman.com/{}",
            "OyunProfesyonel": "https://www.oyunprofesyonel.com/{}",
            "OyunUsta": "https://www.oyunusta.com/{}",
            "OyunDahi": "https://www.oyundahi.com/{}",
            "OyunYetenek": "https://www.oyunyetenek.com/{}",
            "OyunZeka": "https://www.oyunzeka.com/{}",
            "OyunStrateji": "https://www.oyunstrateji.com/{}",
            "OyunTaktik": "https://www.oyuntaktik.com/{}",
            "OyunPlan": "https://www.oyunplan.com/{}",
            "OyunHedef": "https://www.oyunhedef.com/{}",
            "OyunAmaç": "https://www.oyunamac.com/{}",
            "OyunMisyon": "https://www.oyunmisyon.com/{}",
            "OyunVizyon": "https://www.oyunvizyon.com/{}",
            "OyunHayal": "https://www.oyunhayal.com/{}",
            "OyunDusunce": "https://www.oyundusunce.com/{}",
            "OyunFikir": "https://www.oyunfikir.com/{}",
            "OyunYenilik": "https://www.oyunyenilik.com/{}",
            "OyunIcra": "https://www.oyunicra.com/{}",
            "OyunUygulama": "https://www.oyunuygulama.com/{}",
            "OyunPratik": "https://www.oyunpratik.com/{}",
            "OyunDeneyim": "https://www.oyundeneyim.com/{}",
            "OyunTecrube": "https://www.oyuntecrube.com/{}",
            "OyunBilgi": "https://www.oyunbilgi.com/{}",
            "OyunBilim": "https://www.oyunbilim.com/{}",
            "OyunArastirma": "https://www.oyunarastirma.com/{}",
            "OyunKesif": "https://www.oyunkesif.com/{}",
            "OyunBuluş": "https://www.oyunbulus.com/{}",
            "OyunInovasyon": "https://www.oyuninovasyon.com/{}",
            
        }
        self.results = queue.Queue()
        self.headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
        }
        self.timeout = 5
        self.max_threads = 25
        self.max_retries = 3
        self._init_database()

    def _init_database(self) -> None:
        with sqlite3.connect('kullanici_sonuclari.db') as conn:
            c = conn.cursor()
            c.execute('''CREATE TABLE IF NOT EXISTS sonuclar
                        (kullanici_adi TEXT, platform TEXT, sonuc TEXT, zaman TEXT)''')
            conn.commit()

    def _save_to_db(self, username: str, platform: str, result: str) -> None:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with sqlite3.connect('kullanici_sonuclari.db') as conn:
            c = conn.cursor()
            c.execute("INSERT INTO sonuclar VALUES (?, ?, ?, ?)",
                     (username, platform, result, timestamp))
            conn.commit()

    def check_single_site(self, site: str, url_template: str, username: str) -> None:
        url = url_template.format(quote(username))
        for attempt in range(self.max_retries):
            try:
                response = requests.get(
                    url,
                    headers=self.headers,
                    timeout=self.timeout
                )
                status = response.status_code
                if status == 200:
                    result = f"[✓] {site}: Bulundu! - {url}"
                elif status == 404:
                    result = f"[✗] {site}: Bulunamadı"
                elif status == 403:
                    result = f"[?] {site}: Erişim Engellendi (403) - {url}"
                elif status == 429:
                    result = f"[!] {site}: Çok Fazla İstek (429) - {url}"
                    time.sleep(2 ** attempt)
                    continue
                else:
                    result = f"[?] {site}: Durum Kodu {status} - {url}"
                break
            except requests.RequestException as e:
                if attempt == self.max_retries - 1:
                    result = f"[!] {site}: Hata - {str(e)}"
                else:
                    time.sleep(2 ** attempt)
                    continue
        self.results.put((site, result))
        self._save_to_db(username, site, result)

    def check_username(self, username: str) -> Dict[str, str]:
        animate_text(f"↳ '{username}' Taranıyor...", Fore.YELLOW, 0.02)
        threads = []
        result_dict = {}
        for site, url_template in self.sites.items():
            thread = threading.Thread(
                target=self.check_single_site,
                args=(site, url_template, username)
            )
            threads.append(thread)
            thread.start()
            if len(threads) >= self.max_threads:
                for t in threads:
                    t.join()
                threads = []
        for t in threads:
            t.join()
        while not self.results.empty():
            site, result = self.results.get()
            result_dict[site] = result
            if "[✓]" in result:
                animate_text(result, Fore.GREEN, 0.01)
            elif "[✗]" in result:
                animate_text(result, Fore.RED, 0.01)
            else:
                animate_text(result, Fore.MAGENTA, 0.01)
        return result_dict

    def check_multiple_usernames(self, usernames: List[str]) -> None:
        for username in usernames:
            start_time = time.time()
            self.check_username(username)
            end_time = time.time()
            animate_text(f"✓ '{username}' Tarama Tamamlandı | Süre: {end_time - start_time:.2f}s", Fore.CYAN, 0.02)

def main():
    startup_animation()
    if not check_password():
        return
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Fore.GREEN + ARIVA_BANNER + Style.RESET_ALL)
    animate_text("ARIVA Kullanıcı Adı Denetleyicisi", Fore.CYAN, 0.02)
    animate_text("Çıkış: 'q' | Çoklu Kullanıcı: user1,user2,user3", Fore.YELLOW, 0.02)
    print(Fore.CYAN + "═" * 50 + Style.RESET_ALL)
    checker = UsernameChecker()
    while True:
        animate_text("\nTaranacak Kullanıcı Adları: ", Fore.MAGENTA, 0.02)
        input_str = input().strip()
        if input_str.lower() == 'q':
            animate_text("ARIVA Kapatılıyor...", Fore.RED, 0.03)
            time.sleep(1)
            break
        if not input_str:
            animate_text("✗ Hata: Kullanıcı Adı Giriniz!", Fore.RED, 0.02)
            continue
        usernames = [u.strip() for u in input_str.split(',')]
        checker.check_multiple_usernames(usernames)
        print(Fore.CYAN + "═" * 50 + Style.RESET_ALL)

if __name__ == "__main__":
    main()
